services:
  - type: web
    name: telegram-loyalty-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        value: your-service-name.onrender.com
      - key: WEBHOOK_PATH
        value: /webhook/your_bot_token