services:
  - type: web
    name: hlp-loyalty-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python hotel-quiz-bot.py
    envVars:
      - key: CSV_PATH
        value: hotel_data.csv
      - key: TELEGRAM_BOT_TOKEN
        value: 8022857403:AAEvoVF6qmOzqp5UUP3rm4vZKzx84bnbUZ0
      - key: WEBHOOK_HOST
        value: hlp-loyalty-bot.onrender.com